### ISSUE TITLE
Setup menu options missing

### ISSUE THREAD

**Issue by davidGravityLab** [dannysummerlin/force-navigator#32]
Great work on the new release, pretty much all the stuff that bothered me you fixed.

When there are certain menu options missing, is the best way to notify you to raise a ticket? I'm not sure how dynamic the process is, or if you just have to add them all manually.

The first one I've noticed is the "DKIM Keys" screen - /lightning/setup/EmailDKIMList/home

This isn't urgent in any way, just thought I'd get it logged.

**Comment by dannysummerlinjstartorg** [comment]
Hi there, glad the updates are helping! This is the perfect place to register when you know it is missing something (or have any other issue). Thanks for catching those, I have added them here: https://github.com/dannysummerlin/force-navigator/commit/ddc85933667d041f58b90d7c5e94bd0d2f0850fc so it will be fixed in the next update, which should be coming soon
